"""Genera tok_unicode_han.h: tabella di range per \\p{Han} (Script=Han), la
classe che il pre-tokenizer Kimi-K2 usa nel suo primo ramo ([\\p{Han}]+) e
come ESCLUSIONE (&&[^\\p{Han}]) nei rami lettera.

Ground truth: tiktoken stesso. Il tokenizer K2 di riferimento e' tiktoken
(fancy-regex): interroghiamo QUELLA engine codepoint per codepoint con un
pattern [\\p{Han}]+ e una Encoding a soli byte -- encode() ritorna vuoto se
il codepoint non matcha (le span non coperte dal pattern vengono scartate).
Cosi' la tabella C coincide per costruzione con cio' che l'oracolo usa,
qualunque versione Unicode spedisca fancy-regex.

Eseguire una volta:  python3 tools/gen_unicode_han.py > tok_unicode_han.h
(richiede: pip install tiktoken)
"""
import sys

import tiktoken

ranks = {bytes([b]): b for b in range(256)}
enc = tiktoken.Encoding(name="han_probe", pat_str=r"[\p{Han}]+",
                        mergeable_ranks=ranks, special_tokens={})

def is_han(cp: int) -> bool:
    return bool(enc.encode(chr(cp)))

out = []
lo = None
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF:      # surrogati: mai
        if lo is not None:
            out.append((lo, cp - 1)); lo = None
        continue
    if is_han(cp):
        if lo is None:
            lo = cp
    else:
        if lo is not None:
            out.append((lo, cp - 1)); lo = None
if lo is not None:
    out.append((lo, 0x10FFFF))

n = sum(hi - lo + 1 for lo, hi in out)
print("/* GENERATED by tools/gen_unicode_han.py -- do not edit by hand.")
print(f" * \\p{{Han}} per la regex engine di tiktoken: {n} codepoint in {len(out)} range. */")
print("#ifndef TOK_UNICODE_HAN_H\n#define TOK_UNICODE_HAN_H\n#include <stdint.h>\n")
print("static const uint32_t uni_HAN[][2] = {")
for i in range(0, len(out), 6):
    chunk = "".join(f"{{0x{a:X},0x{b:X}}}," for a, b in out[i:i + 6])
    print("    " + chunk)
print("};")
print(f"static const int uni_HAN_n = {len(out)};\n")
print("static inline int is_HAN(uint32_t c){ return uni_in(uni_HAN,uni_HAN_n,c); }")
print("\n#endif")
